In [52]:
#generate a matrix 

import numpy as np

height_list = [6.0, 5.4, 7.6, 6.1,6.04, 8.3]

#convert to numpy array 

height_array = np.array(height_list)

print (type(height_array))
print (height_array)


<class 'numpy.ndarray'>
[6.   5.4  7.6  6.1  6.04 8.3 ]


In [53]:
#create an matrix between 1 and 100

np.ndarray (shape=(3,5), dtype =int)

array([[ 8070450532247928832,  8070450532247928832,                    8,
                           0,                    0],
       [                   0,                    0,                    0,
                           0,                    0],
       [                   0,                    0,                    0,
            -140294792513145, -3458755745396030046]])

In [19]:
x= np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
x= np.arange(1,101)

#resapre the array to 20 rows and 5 columns (20x5 matrix)
np.reshape(x, (20,5))

#

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [28]:
math1= np.arange(1,101)

#resapre the array to 20 rows and 5 columns (20x5 matrix)
np.reshape(math1, (20,5))

#subtract 50 from matrix 

math1 = math1 -50
np.reshape(math1, (20,5))

print (math1)

[-49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33 -32
 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14
 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4
   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50]


In [40]:
#addition

logo = np.arange(1,101).reshape(20,5)
logo = logo -50
print (logo)

[[-49 -48 -47 -46 -45]
 [-44 -43 -42 -41 -40]
 [-39 -38 -37 -36 -35]
 [-34 -33 -32 -31 -30]
 [-29 -28 -27 -26 -25]
 [-24 -23 -22 -21 -20]
 [-19 -18 -17 -16 -15]
 [-14 -13 -12 -11 -10]
 [ -9  -8  -7  -6  -5]
 [ -4  -3  -2  -1   0]
 [  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]]


In [44]:
np.dot(logo, logo.T)

array([[ 11055,   9880,   8705,   7530,   6355,   5180,   4005,   2830,
          1655,    480,   -695,  -1870,  -3045,  -4220,  -5395,  -6570,
         -7745,  -8920, -10095, -11270],
       [  9880,   8830,   7780,   6730,   5680,   4630,   3580,   2530,
          1480,    430,   -620,  -1670,  -2720,  -3770,  -4820,  -5870,
         -6920,  -7970,  -9020, -10070],
       [  8705,   7780,   6855,   5930,   5005,   4080,   3155,   2230,
          1305,    380,   -545,  -1470,  -2395,  -3320,  -4245,  -5170,
         -6095,  -7020,  -7945,  -8870],
       [  7530,   6730,   5930,   5130,   4330,   3530,   2730,   1930,
          1130,    330,   -470,  -1270,  -2070,  -2870,  -3670,  -4470,
         -5270,  -6070,  -6870,  -7670],
       [  6355,   5680,   5005,   4330,   3655,   2980,   2305,   1630,
           955,    280,   -395,  -1070,  -1745,  -2420,  -3095,  -3770,
         -4445,  -5120,  -5795,  -6470],
       [  5180,   4630,   4080,   3530,   2980,   2430,   1880,   1330,
   

In [36]:
logo *10

array([[-490, -480, -470, -460, -450],
       [-440, -430, -420, -410, -400],
       [-390, -380, -370, -360, -350],
       [-340, -330, -320, -310, -300],
       [-290, -280, -270, -260, -250],
       [-240, -230, -220, -210, -200],
       [-190, -180, -170, -160, -150],
       [-140, -130, -120, -110, -100],
       [ -90,  -80,  -70,  -60,  -50],
       [ -40,  -30,  -20,  -10,    0],
       [  10,   20,   30,   40,   50],
       [  60,   70,   80,   90,  100],
       [ 110,  120,  130,  140,  150],
       [ 160,  170,  180,  190,  200],
       [ 210,  220,  230,  240,  250],
       [ 260,  270,  280,  290,  300],
       [ 310,  320,  330,  340,  350],
       [ 360,  370,  380,  390,  400],
       [ 410,  420,  430,  440,  450],
       [ 460,  470,  480,  490,  500]])

In [55]:
logo = logo *logo
print (logo)

[[5764801 5308416 4879681 4477456 4100625]
 [3748096 3418801 3111696 2825761 2560000]
 [2313441 2085136 1874161 1679616 1500625]
 [1336336 1185921 1048576  923521  810000]
 [ 707281  614656  531441  456976  390625]
 [ 331776  279841  234256  194481  160000]
 [ 130321  104976   83521   65536   50625]
 [  38416   28561   20736   14641   10000]
 [   6561    4096    2401    1296     625]
 [    256      81      16       1       0]
 [      1      16      81     256     625]
 [   1296    2401    4096    6561   10000]
 [  14641   20736   28561   38416   50625]
 [  65536   83521  104976  130321  160000]
 [ 194481  234256  279841  331776  390625]
 [ 456976  531441  614656  707281  810000]
 [ 923521 1048576 1185921 1336336 1500625]
 [1679616 1874161 2085136 2313441 2560000]
 [2825761 3111696 3418801 3748096 4100625]
 [4477456 4879681 5308416 5764801 6250000]]
