In [57]:
#create a random 5x5 matrix 
import random 
import numpy as np 
np.random.seed(seed =60)
five_times_five = np.random.randint(0, 50, size =(5,5))
five_times_five


array([[13,  1,  6, 10, 15],
       [35,  8, 17, 34, 33],
       [23, 42, 40, 44, 34],
       [40,  3, 44, 32, 26],
       [ 3, 47, 42, 36, 32]])

In [58]:
#finding specific rows and columns 

#first row 

print(five_times_five[0])

[13  1  6 10 15]


In [59]:
#first row, column 1
print(five_times_five[0,0])

13


In [60]:
#column 1 (of each row)

for x in range (0, 5): 
    print (five_times_five[x,0])

13
35
23
40
3


In [61]:
#other way: of column 1 (each row)
five_times_five[:,0]

array([13, 35, 23, 40,  3])

In [62]:
#finding the mean of the matrix 

five_times_five.mean()


26.4

In [56]:
#mean of first row

five_times_five[0,:].mean()

9.0